#!/bin/bash

# kellaaja järgi tervituse muutus, kella  võtab süteemist

aeg=$(date +%H)

if [[ "$aeg" -ge "6" && "$aeg" -lt "12" ]]

then
	echo "Tere hommikust, $USER!"

elif [[ "$aeg" -ge "12" && "$aeg" -lt "18" ]]

then
	echo "Tere päevast, $USER!"

elif [[ "$aeg" -ge "18" && "$aeg" -lt "22" ]]

then
	echo "Head õhtust, $USER!"

elif [[ "$aeg" -ge "22" && "$aeg" -lt "24" || "$aeg" -ge "0" && "$aeg" -lt "6" ]]

then
	echo "Head ööd, $USER!"

else
	echo "Vale sisend"

fi
