#!/bin/bash

# vanuse tingimuslaused


echo "Sisesta oma vanus."

	read vanus

if [[ $vanus -ge 0 && $vanus -lt 11 ]]

then

	echo "Oled laps"

elif [[ $vanus -ge 11 && $vanus -lt 18 ]]

then

	echo "Oled nooruk"

elif [[ $vanus -ge 18 && $vanus -lt 63 ]]

then

	echo "Oled täiskasvanu"

elif [[ $vanus -ge 63 ]]

then

	echo "Oled seenior"

else

	echo "vigane sisend"

fi
